export const stations_list = [
    {   
        station_id: 1,
        title: "Станция на улице Пушкина",
        description: "Установлена на улице Пушкина, 1. Показывает температуру и влажность воздуха.",
        current_temp: 15,
        current_humidity: 60,
        current_pressure: 1012,
        measurement_time: "2023-10-01T12:00:00Z",
        status: "online",
    },
    {   
        station_id: 2,
        title: "Станция на улице Лермонтова",
        description: "Установлена на улице Лермонтова, 15. Показывает температуру, влажность и давление воздуха.",
        current_temp: 18,
        current_humidity: 55,
        current_pressure: 1010,
        measurement_time: "2023-10-01T12:05:00Z",
        status: "online",
    },
    {   
        station_id: 3,
        title: "Станция на улице Чехова",
        description: "Установлена на улице Чехова, 22. Показывает температуру, влажность и скорость ветра.",
        current_temp: 20,
        current_humidity: 50,
        current_pressure: 1008,
        measurement_time: "2023-10-01T12:10:00Z",
        status: "online",
    },
    {   
        station_id: 4,
        title: "Станция на улице Толстого",
        description: "Установлена на улице Толстого, 8. Показывает температуру, влажность и уровень осадков.",
        current_temp: 17,
        current_humidity: 65,
        current_pressure: 1015,
        measurement_time: "2023-10-01T12:15:00Z",
        status: "online",
    },
    {   
        station_id: 5,
        title: "Станция на улице Гоголя",
        description: "Установлена на улице Гоголя, 10. Показывает температуру, влажность и качество воздуха.",
        current_temp: 16,
        current_humidity: 70,
        current_pressure: 1013,
        measurement_time: "2023-10-01T12:20:00Z",
        status: "online",
    },
    {   
        station_id: 6,
        title: "Станция на улице Тургенева",
        description: "Установлена на улице Тургенева, 5. Показывает температуру, влажность и ультрафиолетовый индекс.",
        current_temp: 19,
        current_humidity: 58,
        current_pressure: 1011,
        measurement_time: "2023-10-01T12:25:00Z",
        status: "online",
    },
]
    
