export type station = {
    station_id: number,
    title: string,
    description: string,
    current_co2: number,
    current_temp: number,
    current_humidity: number,
    current_pressure: number,
    measurement_time: string,
    status: string,
}

export const stations_list = [
    {   
        station_id: 1,
        title: "Станция на улице Пушкина",
        description: "Установлена на улице Пушкина, 1. Показывает температуру и влажность воздуха.",
        current_co2: 0.03,
        current_temp: 15.2,
        current_humidity: 60,
        current_pressure: 1012,
        measurement_time: "2023-10-01T12:00:00Z",
        status: "online",
    },
    {   
        station_id: 2,
        title: "Станция на улице Лермонтова",
        description: "Установлена на улице Лермонтова, 15. Показывает температуру, влажность и давление воздуха.",
        current_co2: 0.04,
        current_temp: 18.5,
        current_humidity: 55,
        current_pressure: 1010,
        measurement_time: "2023-10-01T12:05:00Z",
        status: "online",
    },
    {   
        station_id: 3,
        title: "Станция на улице Чехова",
        description: "Установлена на улице Чехова, 22. Показывает температуру, влажность и скорость ветра.",
        current_co2: 0.05,
        current_temp: 20.3,
        current_humidity: 50,
        current_pressure: 1008,
        measurement_time: "2023-10-01T12:10:00Z",
        status: "online",
    },
    {   
        station_id: 4,
        title: "Станция на улице Толстого",
        description: "Установлена на улице Толстого, 8. Показывает температуру, влажность и уровень осадков.",
        current_co2: 0.06,
        current_temp: 17.7,
        current_humidity: 65,
        current_pressure: 1015,
        measurement_time: "2023-10-01T12:15:00Z",
        status: "online",
    },
    {   
        station_id: 5,
        title: "Станция на улице Гоголя",
        description: "Установлена на улице Гоголя, 10. Показывает температуру, влажность и качество воздуха.",
        current_co2: 0.07,
        current_temp: 16.4,
        current_humidity: 70,
        current_pressure: 1013,
        measurement_time: "2023-10-01T12:20:00Z",
        status: "online",
    },
    {   
        station_id: 6,
        title: "Станция на улице Тургенева",
        description: "Установлена на улице Тургенева, 5. Показывает температуру, влажность и ультрафиолетовый индекс.",
        current_co2: 0.03,
        current_temp: 19.1,
        current_humidity: 58,
        current_pressure: 1011,
        measurement_time: "2023-10-01T12:25:00Z",
        status: "online",
    },
    {   
        station_id: 7,
        title: "Станция на улице Достоевского",
        description: "Установлена на улице Достоевского, 12. Показывает температуру, влажность и уровень шума.",
        current_co2: 0.02,
        current_temp: 21.6,
        current_humidity: 52,
        current_pressure: 1009,
        measurement_time: "2023-10-01T12:30:00Z",
        status: "online",
    },
    {   
        station_id: 8,
        title: "Станция на улице Гончарова",
        description: "Установлена на улице Гончарова, 3. Показывает температуру, влажность и уровень загрязнения.",
        current_co2: 0.01,
        current_temp: 14.8,
        current_humidity: 68,
        current_pressure: 1014,
        measurement_time: "2023-10-01T12:35:00Z",
        status: "online",
    },
    {   
        station_id: 9,
        title: "Станция на улице Некрасова",
        description: "Установлена на улице Некрасова, 7. Показывает температуру, влажность и уровень радиации.",
        current_co2: 0.08,
        current_temp: 22.3,
        current_humidity: 54,
        current_pressure: 1010,
        measurement_time: "2023-10-01T12:40:00Z",
        status: "online",
    },
    {   
        station_id: 10,
        title: "Станция на улице Белинского",
        description: "Установлена на улице Белинского, 9. Показывает температуру, влажность и уровень пыльцы.",
        current_co2: 0.06,
        current_temp: 13.9,
        current_humidity: 72,
        current_pressure: 1016,
        measurement_time: "2023-10-01T12:45:00Z",
        status: "online",
    },
    {   
        station_id: 11,
        title: "Станция на улице Крылова",
        description: "Установлена на улице Крылова, 4. Показывает температуру, влажность и уровень озона.",
        current_co2: 0.04,
        current_temp: 23.7,
        current_humidity: 56,
        current_pressure: 1007,
        measurement_time: "2023-10-01T12:50:00Z",
        status: "online",
    },
    {   
        station_id: 12,
        title: "Станция на улице Жуковского",
        description: "Установлена на улице Жуковского, 6. Показывает температуру, влажность и уровень углекислого газа.",
        current_co2: 0.05,
        current_temp: 12.5,
        current_humidity: 74,
        current_pressure: 1017,
        measurement_time: "2023-10-01T12:55:00Z",
        status: "online",
    },
    {   
        station_id: 13,
        title: "Станция на улице Тютчева",
        description: "Установлена на улице Тютчева, 11. Показывает температуру, влажность и уровень сероводорода.",
        current_co2: 0.07,
        current_temp: 24.2,
        current_humidity: 53,
        current_pressure: 1006,
        measurement_time: "2023-10-01T13:00:00Z",
        status: "online",
    },
    {   
        station_id: 14,
        title: "Станция на улице Грибоедова",
        description: "Установлена на улице Грибоедова, 2. Показывает температуру, влажность и уровень метана.",
        current_co2: 0.08,
        current_temp: 25.4,
        current_humidity: 57,
        current_pressure: 1005,
        measurement_time: "2023-10-01T13:05:00Z",
        status: "online",
    },
    {   
        station_id: 15,
        title: "Станция на улице Салтыкова-Щедрина",
        description: "Установлена на улице Салтыкова-Щедрина, 14. Показывает температуру, влажность и уровень аммиака.",
        current_co2: 0.09,
        current_temp: 26.8,
        current_humidity: 59,
        current_pressure: 1004,
        measurement_time: "2023-10-01T13:10:00Z",
        status: "online",
    },
    {   
        station_id: 16,
        title: "Станция на улице Ломоносова",
        description: "Установлена на улице Ломоносова, 13. Показывает температуру, влажность и уровень бензола.",
        current_co2: 0.07,
        current_temp: 27.1,
        current_humidity: 61,
        current_pressure: 1003,
        measurement_time: "2023-10-01T13:15:00Z",
        status: "online",
    },
]

